version: '3.8'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: mongodb
    ports:
      - "27017:27017"

  nodejs:
    build: .
    container_name: nodejs
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
